create table if not exists public.trade_ledger (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  symbol text not null,
  mode text not null,
  action text not null,
  status text not null,
  reason text not null,
  notional double precision not null,
  equity double precision,
  cash double precision
);

create index if not exists trade_ledger_timestamp_idx on public.trade_ledger (timestamp desc);

create table if not exists public.equity_curve (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  equity double precision not null,
  cash double precision not null,
  mode text not null
);

create index if not exists equity_curve_timestamp_idx on public.equity_curve (timestamp asc);

create table if not exists public.latest_signal (
  id text primary key,
  mode text not null,
  label text not null,
  message text not null,
  reason text not null,
  hourly_drawdown double precision not null,
  updated_at timestamptz
);

alter table public.trade_ledger enable row level security;
alter table public.equity_curve enable row level security;
alter table public.latest_signal enable row level security;

create policy "service role full access trade_ledger"
on public.trade_ledger
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role full access equity_curve"
on public.equity_curve
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service role full access latest_signal"
on public.latest_signal
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
